[tools]
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
PYTHONPATH = "."

[hooks]
enter = "echo 'Welcome to the template project'"

[tasks.app]
run = 'uv run python aicb/app.py'


[tasks.interface]
run = 'uv run streamlit run aicb/interface.py'

[tasks.test]
run = 'uv run pytest'

[tasks.cov]
run = [
  'uv run pytest --cov=aicb --cov-report=xml',
  'uv run coverage-badge -o docs/coverage.svg -f',
  'uv run interrogate --generate-badge docs/interrogate.svg',
]

[tasks.sec]
run = ['uv run bandit -r aicb']

[tasks.cov-html]
run = 'uv run pytest --cov=aicb --cov-report=html'

[tasks.pyright]
run = 'uv run pyright'
